// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <APProtocolBuffers/ProtocolBuffers.h>

@class AndroidParameter;
@class DynamicResourceInfo;
@class DynamicResourceItem;
@class DynamicResourceRequest;
@class DynamicResourceResult;
@class ExtraData;
@class IOSParameter;

typedef NS_ENUM(SInt32, DynamicResourceBizType) {
  DynamicResourceBizTypeUnknown = 0,
  DynamicResourceBizTypeHotpatch = 1,
  DynamicResourceBizTypeBundle = 2,
  DynamicResourceBizTypeBirdnest = 3,
  DynamicResourceBizTypeNebula = 4,
  DynamicResourceBizTypeIosdynamic = 5,
  DynamicResourceBizTypeCmd = 6,
};

typedef NS_ENUM(SInt32, AndroidVmType) {
  AndroidVmTypeAll = 0,
  AndroidVmTypeArt = 1,
  AndroidVmTypeDalvik = 2,
  AndroidVmTypeLemur = 3,
  AndroidVmTypeAoc = 4,
};

@interface DynamicResourceResult : APPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasSuccess;
@property (readonly) BOOL hasMessage;
@property (nonatomic)BOOL success;
@property (nonatomic,strong) NSString* message;
@property (nonatomic,strong) NSMutableArray * info;
@end

@interface DynamicResourceInfo : APPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasBizType;
@property (readonly) BOOL hasSuccess;
@property (readonly) BOOL hasMessage;
@property (readonly) BOOL hasVersion;
@property (readonly) BOOL hasRollback;
@property (nonatomic)DynamicResourceBizType bizType;
@property (nonatomic)BOOL success;
@property (nonatomic,strong) NSString* message;
@property (nonatomic,strong) NSString* version;
@property (nonatomic)BOOL rollback;
@property (nonatomic,strong) NSMutableArray * item;
@end

@interface DynamicResourceItem : APPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasResId;
@property (readonly) BOOL hasResVersion;
@property (readonly) BOOL hasResType;
@property (readonly) BOOL hasFileMd5;
@property (readonly) BOOL hasFileUrl;
@property (readonly) BOOL hasFileContent;
@property (readonly) BOOL hasResStatus;
@property (readonly) BOOL hasIssueDesc;
@property (readonly) BOOL hasLazyLoad;
@property (nonatomic,strong) NSString* resId;
@property (nonatomic,strong) NSString* resVersion;
@property (nonatomic,strong) NSString* resType;
@property (nonatomic,strong) NSString* fileMd5;
@property (nonatomic,strong) NSString* fileUrl;
@property (nonatomic,strong) NSString* fileContent;
@property (nonatomic)SInt32 resStatus;
@property (nonatomic,strong) NSMutableArray * resExtraData;
@property (nonatomic,strong) NSString* issueDesc;
@property (nonatomic)SInt32 lazyLoad;
@property (nonatomic,strong) NSString* frameworkId;
@property (nonatomic)SInt32 quickRun;
@end

@interface ExtraData : APPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasKey;
@property (readonly) BOOL hasValue;
@property (nonatomic,strong) NSString* key;
@property (nonatomic,strong) NSString* value;
@end

@interface DynamicResourceRequest : APPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasProductId;
@property (readonly) BOOL hasProductVersion;
@property (readonly) BOOL hasClientId;
@property (readonly) BOOL hasPhoneBrand;
@property (readonly) BOOL hasPhoneModel;
@property (readonly) BOOL hasUserId;
@property (readonly) BOOL hasExtraInfo;
@property (readonly) BOOL hasNetType;
@property (readonly) BOOL hasAndroidParam;
@property (readonly) BOOL hasIosParam;
@property (readonly) BOOL hasDynamicResourceType;
@property (readonly) BOOL hasUtdid;
@property (nonatomic,strong) NSString* productId;
@property (nonatomic,strong) NSString* productVersion;
@property (nonatomic,strong) NSString* clientId;
@property (nonatomic,strong) NSString* phoneBrand;
@property (nonatomic,strong) NSString* phoneModel;
@property (nonatomic,strong) NSString* userId;
@property (nonatomic,strong) NSString* extraInfo;
@property (nonatomic,strong) NSString* netType;
@property (nonatomic,strong) AndroidParameter* androidParam;
@property (nonatomic,strong) IOSParameter* iosParam;
@property (nonatomic,strong) NSString* dynamicResourceType;
@property (nonatomic,strong) NSMutableArray * cmdUuid;
@property (nonatomic,strong) NSString* utdid;
@end

@interface AndroidParameter : APPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasVmType;
@property (readonly) BOOL hasReleaseVersion;
@property (readonly) BOOL hasChannel;
@property (readonly) BOOL hasApiLevel;
@property (readonly) BOOL hasBandageVersion;
@property (readonly) BOOL hasBundleVersion;
@property (readonly) BOOL hasBirdnestVersion;
@property (readonly) BOOL hasNebulaVersion;
@property (readonly) BOOL hasIssueDesc;
@property (nonatomic)AndroidVmType vmType;
@property (nonatomic,strong) NSString* releaseVersion;
@property (nonatomic,strong) NSString* channel;
@property (nonatomic,strong) NSString* apiLevel;
@property (nonatomic,strong) NSString* bandageVersion;
@property (nonatomic,strong) NSString* bundleVersion;
@property (nonatomic,strong) NSString* birdnestVersion;
@property (nonatomic,strong) NSString* nebulaVersion;
@property (nonatomic,strong) NSString* issueDesc;
@end

@interface IOSParameter : APPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasOsVersion;
@property (readonly) BOOL hasBirdnestVersion;
@property (readonly) BOOL hasNebulaVersion;
@property (readonly) BOOL hasBundleVersion;
@property (nonatomic,strong) NSString* osVersion;
@property (nonatomic,strong) NSMutableArray * patchUuid;
@property (nonatomic,strong) NSString* birdnestVersion;
@property (nonatomic,strong) NSString* nebulaVersion;
@property (nonatomic,strong) NSString* bundleVersion;
@end

